### ISSUE TITLE
Can't dump NAND flash

### ISSUE THREAD

**Issue by padremayi** [ClusterM/hakchi2#1247]
I can't dump the NAND flash, application version 2.0.30.14.

I see this in the terminal window:
```
Error: Can't write to USB   at com.clusterrr.FelLib.Fel.WriteToUSB(Byte[] buffer) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 196
   at com.clusterrr.FelLib.Fel.FelWrite(Byte[] buffer) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 228
   at com.clusterrr.FelLib.Fel.FelRequest(RequestType command) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 250
   at com.clusterrr.FelLib.Fel.VerifyDevice() in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 264
   at com.clusterrr.FelLib.Fel.Open(UInt16 vid, UInt16 pid) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 155
```
Why application point to **D:\Projects\C#\hakchi2\FelLib\Fel.cs**?

Many thanks for the application

**Comment by ChaoticRapier** [comment]
Did you figure this one out yet by any chance?
