### ISSUE TITLE
error after using debug

### ISSUE THREAD

**Issue by Gladdy1976** [ClusterM/hakchi2#1251]
Base directory: C:\Users\danan\AppData\Local\Temp\Rar$EXa8732.26071\hakchi2_debug
Loading config
Starting, version: 2.0.30.14
git commit: 00574c4 (dirty)
Executing task: LoadGames
Loading C:\Users\danan\AppData\Local\Temp\Rar$EXa8732.26071\hakchi2_debug\data\nescarts.xml
Loading C:\Users\danan\AppData\Local\Temp\Rar$EXa8732.26071\hakchi2_debug\data\snescarts.xml
SNES XML loading done, 786 roms total
NES XML loading done, 2150 roms total
Saving config
Executing task: LoadGames
Saving config
Executing task: FlashKernel
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 32 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
Device detection successful
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 32 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 128 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 32 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
Device detection successful
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 32 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 128 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 32 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 48 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
-> 16 bytes
Error: USB read error: IoTimedOut   at com.clusterrr.FelLib.Fel.ReadFromUSB(Byte[] buffer, Int32 offset, Int32 length) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 208
   at com.clusterrr.FelLib.Fel.ReadFromUSB(UInt32 length) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 217
   at com.clusterrr.FelLib.Fel.FelWrite(Byte[] buffer) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 229
   at com.clusterrr.FelLib.Fel.FelRequest(RequestType command) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 250
   at com.clusterrr.FelLib.Fel.VerifyDevice() in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 264
   at com.clusterrr.FelLib.Fel.Open(UInt16 vid, UInt16 pid) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 155
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 32 bytes
<- 16 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
Error: Exception of type 'com.clusterrr.FelLib.FelParseException' was thrown.   at com.clusterrr.FelLib.AWFELVerifyDeviceResponse..ctor(Byte[] data) in D:\Projects\C#\hakchi2\FelLib\AWFELVerifyDeviceResponse.cs:line 26
   at com.clusterrr.FelLib.Fel.VerifyDevice() in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 275
   at com.clusterrr.FelLib.Fel.Open(UInt16 vid, UInt16 pid) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 155
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 32 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
Executing: C:\Users\danan\AppData\Local\Temp\Rar$EXa8732.26071\hakchi2_debug\tools\unpackbootimg.exe
Arguments: -i "C:\Users\danan\AppData\Local\Temp\Rar$EXa8732.26071\hakchi2_debug\temp\kernel.img" -o "C:\Users\danan\AppData\Local\Temp\Rar$EXa8732.26071\hakchi2_debug\temp\kernel"
Directory: C:\Users\danan\AppData\Local\Temp\Rar$EXa8732.26071\hakchi2_debug
Output:
BOARD_KERNEL_CMDLINE root=/dev/nandb decrypt ro console=ttyS0,115200 loglevel=4 ion_cma_512m=16m coherent_pool=4m consoleblank=0
BOARD_KERNEL_BASE 40000000
BOARD_NAME
BOARD_PAGE_SIZE 2048
BOARD_KERNEL_OFFSET 00008000
BOARD_RAMDISK_OFFSET 01000000
BOARD_TAGS_OFFSET 00000100

Exit code: 0
Executing: C:\Users\danan\AppData\Local\Temp\Rar$EXa8732.26071\hakchi2_debug\tools\xz.exe
Arguments: -dc "C:\Users\danan\AppData\Local\Temp\Rar$EXa8732.26071\hakchi2_debug\temp\kernel\kernel.img-ramdisk.gz"
Directory: C:\Users\danan\AppData\Local\Temp\Rar$EXa8732.26071\hakchi2_debug
Errors:
xz: C:\Users\danan\AppData\Local\Temp\Rar$EXa8732.26071\hakchi2_debug\temp\kernel\kernel.img-ramdisk.gz: Compressed data is corrupt

Exit code: 1
Executing: C:\Users\danan\AppData\Local\Temp\Rar$EXa8732.26071\hakchi2_debug\tools\lzop.exe
Arguments: -d "C:\Users\danan\AppData\Local\Temp\Rar$EXa8732.26071\hakchi2_debug\temp\kernel\kernel.img-ramdisk.gz" -o "C:\Users\danan\AppData\Local\Temp\Rar$EXa8732.26071\hakchi2_debug\temp\kernel\initramfs.cpio"
Directory: C:\Users\danan\AppData\Local\Temp\Rar$EXa8732.26071\hakchi2_debug
Errors:
lzop: c:\users\danan\appdata\local\temp\rar$exa8732.26071\hakchi2_debug\temp\kernel\kernel.img-ramdisk.gz: not a lzop file

Exit code: 1
Can't unpack ramdisk   at com.clusterrr.hakchi_gui.WorkerForm.UnpackRamfs(String kernelPath) in D:\Projects\C#\hakchi2\WorkerForm.cs:line 1253
   at com.clusterrr.hakchi_gui.WorkerForm.DoKernelDump(String dumpPath, Int32 maxProgress, Int32 progress) in D:\Projects\C#\hakchi2\WorkerForm.cs:line 483
   at com.clusterrr.hakchi_gui.WorkerForm.FlashKernel() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 551
   at com.clusterrr.hakchi_gui.WorkerForm.StartThread() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 286
please can some one help 

Cheers Gladdy1976

**Comment by dbelyaev** [comment]
So, you did run a debug build and got this message? 

Please, give more information about what happened, what you were trying to achieve (debug build), steps to reproduce, have you tried it on another machine, what is your OS?

Messages of a type: "I got an error, here is an output <4 pages output quote>" are not so helpful to developers.

Thanks for your time.
