### ISSUE TITLE
Access to the path denied

### ISSUE THREAD

**Issue by DaxFame** [ClusterM/hakchi2#1299]
Access to the path 'C:\Users\Kree\Desktop\hakchi2_0.20\temp\games\snes\000\CLV-P-SACCE' is denied.   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalGetFileDirectoryNames(String path, String userPathOriginal, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searchOption)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at com.clusterrr.hakchi_gui.Program.Main() in D:\Projects\C#\hakchi2\Program.cs:line 125

No virus protection

**Comment by DaxFame** [comment]
Ownership issue
