### ISSUE TITLE
Stuck at DONE! when dumping kernal. 

### ISSUE THREAD

**Issue by Dnyte270** [ClusterM/hakchi2#1302]
Updated Hakchi and when I went to add a game it said I needed to dump my kernal.  I did so but now it just sits on the "DONE!" part of the update for a prolonged period of time.  I waited about 15 minutes of sitting on "DONE!" and just closed the window but it did not complete.  There is no okay, or close button I had to actually X out of the page.  Sitting back on the screen waiting and I cannot go any further.

**Comment by dashydash** [comment]
Hi, had the same problem. I have flashed original kernel with an old version of hakchi 2.20something and then dumped the kernel again in 2.30. it worked for me.

**Comment by ClusterM** [comment]
Debug log please.

**Comment by shinmai** [comment]
Having the same issue, will try @dashydash's workaround, in the meantime, I've uploaded a [full log](https://pastebin.com/QQ1vfKU1) to pastebin, but here's (what I think is) the relevant stuff from after the transfer:

```
Executing: D:\hakchi2_debug\tools\unpackbootimg.exe
Arguments: -i "D:\hakchi2_debug\temp\kernel.img" -o "D:\hakchi2_debug\temp\kernel"
Directory: D:\hakchi2_debug
Exit code: 0
Executing: D:\hakchi2_debug\tools\xz.exe
Arguments: -dc "D:\hakchi2_debug\temp\kernel\kernel.img-ramdisk.gz"
Directory: D:\hakchi2_debug
Exit code: 0
Executing: D:\hakchi2_debug\tools\cpio.exe
Arguments: -imd --no-preserve-owner --quiet -I "..\initramfs.cpio"
Directory: D:\hakchi2_debug\temp\kernel\initramfs
Exit code: 0
Could not find file 'D:\hakchi2_debug\temp\kernel\initramfs\key-file'.   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.ReadAllBytes(String path)
   at com.clusterrr.hakchi_gui.WorkerForm.DoKernelDump(String dumpPath, Int32 maxProgress, Int32 progress)
   at com.clusterrr.hakchi_gui.WorkerForm.StartThread()
```
This is on a fresh hakchi2 install, when first trying to dump. It also pops an error dialog with the WinIOError details. 
Retrying the dump after this, no error is thrown and the only things logged after the transfer are:

```
Executing: D:\hakchi2_debug\tools\unpackbootimg.exe
Arguments: -i "D:\hakchi2_debug\temp\kernel.img" -o "D:\hakchi2_debug\temp\kernel"
Directory: D:\hakchi2_debug
Exit code: 0
Executing: D:\hakchi2_debug\tools\xz.exe
Arguments: -dc "D:\hakchi2_debug\temp\kernel\kernel.img-ramdisk.gz"
Directory: D:\hakchi2_debug
Exit code: 0
Executing: D:\hakchi2_debug\tools\cpio.exe
Arguments: -imd --no-preserve-owner --quiet -I "..\initramfs.cpio"
Directory: D:\hakchi2_debug\temp\kernel\initramfs
```

...and that's when the progress window gets stuck at done.

If others are not having the same file not found error, my issue may be separate.

**Comment by sebastianhaba** [comment]
I have same problem
