### ISSUE TITLE
Games will not export to USB, hakchi CE v3.5.1/3.5.2

### ISSUE THREAD

**Issue by WebbSlingerX** [ClusterM/hakchi2#1439]
Whenever I synced the games to NAND, they work perfectly. Each game folder will contain the following:
1.)   a .desktop file
2.)   2  .png files for cover art
3.)  .7z  file containing the rom. 

However, when I export to my USB drive, the folders ONLY contain the  .desktop file.  Therefore, the games have no covert art, and will not load. I have no idea why this is happening. I've tried different USB flash drives, and both versions of hakchi CE.  What's going on here? :(

**Comment by kozmod** [comment]
I have an error when try export psp game (or psx) to USB-drive.

UnauthorizedAccessException
Access to the path 'D:\Games\hakchi2-ce-3.5.2-release\games\CLV-I-WIUPT\Final_Fantasy_II.iso' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at com.clusterrr.util.TrackableFileStream..ctor(String path, FileMode mode)
   at com.clusterrr.hakchi_gui.Tasks.SyncTask.SyncLocalGames(Tasker tasker, Object syncObject)
   at com.clusterrr.hakchi_gui.Tasks.Tasker.startThread()
--- DEBUGLOG.TXT content ---
Base directory: D:\Games\hakchi2-ce-3.5.2-release (portable mode)
Loading configuration
Starting, version: 3.5.2
Loading libretro core info files
Building libretro core cross index
Loading D:\Games\hakchi2-ce-3.5.2-release\data\nescarts.xml
Loading D:\Games\hakchi2-ce-3.5.2-release\data\snescarts.xml
SNES XML loading done, 786 roms total
NES XML loading done, 2150 roms total
[Upgrade] No upgrade action needed
.....Executing task: LoadGamesTask.LoadGames
Executing task: LoadGamesTask.CreateListViewGroups
Executing task: LoadGamesTask.LoadGamesFromFiles
Loading original games data
Executing task: LoadGamesTask.AssignGroupsToGames
Executing task: LoadGamesTask.AssignListViewGroups
Executing task: LoadGamesTask.UpdateListView
Tasker completed all tasks, conclusion: Success
Local hakchi.hmod version info: boot 1.0.2, kernel 3.4.113.24-madmonkey, script v1.0.4-123
Service added:
    Instance: hakchi
    Type: _ssh._tcp
    IP: 169.254.13.37
    Port: 22
    Txt: hwid=0461872a 86685147 9d1859a7 6c118000, type=snes, region=eur
Attempting to connect to 169.254.13.37...
SSH shell connected
IP Address: 169.254.13.37
Encryption: aes256-ctr
source /hakchi/config; [ "$cf_memboot" = "y" ] # exit code 2
hakchi hwid # exit code 0
Detected device unique ID: 0461872a866851479d1859a76c118000
[ -f /var/version ] && echo "yes" # exit code 0
source /var/version && echo "$bootVersion $kernelVersion $hakchiVersion" # exit code 0
Detected versions: boot 1.0.2, kernel 3.4.113.24-madmonkey, script v1.0.4-123
hakchi eval 'echo "$sftype-$sfregion"' # exit code 0
hakchi currentFirmware # exit code 0
hakchi findGameSyncStorage # exit code 0
hakchi get gamepath # exit code 0
hakchi get rootfs # exit code 0
hakchi get squashfs # exit code 0
Reading p0000_config file
cat /etc/preinit.d/p0000_config # exit code 0
df "$(hakchi findGameSyncStorage)" | tail -n 1 | awk '{ print $2 " | " $3 " | " $4 }' # exit code 0
mount | grep /var/lib/clover/profiles # exit code 1
du -s "$(readlink /var/saves)" | awk '{ print $1 }' # exit code 0
du -d 1 "/var/lib/hakchi/games" | head -n -1 | awk '{ print $2 " | " $1 }' # exit code 0
Storage size: 290,6MB, used: 64,1MB, free: 211,5MB
    Used by all games: 3,5MB
    Used by non multi-boot games: 0,0MB
    Used by current games collection: 3,5MB
    Used by save-states: 4,1MB
    Used by other files (mods, configs, etc.): 56,5MB
    Reserved memory: 30,0MB
    Available for games: 185,0MB
.....Executing task: GameCacheTask.UpdateLocal
hakchi eval 'echo "$squashfs$gamepath"' # exit code 0
[ -d "/var/squashfs/usr/share/games" ] && echo YES || echo NO # exit code 0
ls "/var/squashfs/usr/share/games" -p -1 | grep '/' # exit code 0
Tasker completed all tasks, conclusion: Success
Done refreshing local original games cache.
Success!
......Executing task: AddGamesTask.AddGames
Saving application "CLV-I-WIUPT" as CLV-I-WIUPT
Saving application "Final Fantasy II" as CLV-I-WIUPT
Executing task: AddGamesTask.UpdateListView
Saving application "Final Fantasy II" as CLV-I-WIUPT
Tasker completed all tasks, conclusion: Success
Web request: https://www.google.com/search?q=Final+Fantasy+II+game+(box%7ccover)+art&source=lnms&tbm=isch
Downloading image: https://vignette.wikia.nocookie.net/finalfantasy/images/9/94/Final_Fantasy_II_unused_box_art.jpg/revision/latest?cb=20060224061755
Downloading image: http://2.bp.blogspot.com/-Xx69gAmIWMM/VXr0VdsSrcI/AAAAAAAAF_g/nlY-3aSrGF0/s1600/nes_finalfantasy2_front.png
Downloading image: https://www.mobygames.com/images/covers/l/194617-final-fantasy-ii-snes-front-cover.jpg
Downloading image: http://vgboxart.com/boxes/DS/17719-final-fantasy-ii.jpg
Downloading image: https://vignette.wikia.nocookie.net/finalfantasy/images/4/44/FFXIII-2_NA_Boxart_PS3.png/revision/latest?cb=20111101201958
Downloading image: https://vignette.wikia.nocookie.net/nintendo/images/9/9d/Final_Fantasy_II_(NA).jpg/revision/latest?cb=20120216191410&path-prefix=en
Downloading image: https://images-na.ssl-images-amazon.com/images/I/91J0IKNh7XL._AC_SL1500_.jpg
Downloading image: https://upload.wikimedia.org/wikipedia/en/thumb/d/d8/FF1_USA_boxart.jpg/220px-FF1_USA_boxart.jpg
Downloading image: https://cdn.shopify.com/s/files/1/2781/1778/products/Final_Fantasy_G_2b729112-7153-468c-a5fe-9e221330a49f_1024x1024@2x.jpg?v=1517327624
Downloading image: https://gamefaqs.akamaized.net/box/2/3/2/83232_front.jpg
Downloading image: http://www.ffshrine.org/ffx2/coverscans/ffx2_us.jpg
Downloading image: http://www.hellandheavennet.com/files/final-fantasy-2/box-nes-jp-1.jpg
Downloading image: https://www.mobygames.com/images/covers/l/83387-final-fantasy-ii-snes-back-cover.jpg
Downloading image: https://upload.wikimedia.org/wikipedia/en/thumb/a/a7/Ffxboxart.jpg/220px-Ffxboxart.jpg
Saving selected games
Saving configuration
......Executing task: SyncTask.ExportGames
Executing task: SyncTask.ShowExportDialog
Executing task: SyncTask.BuildMenu
Saving configuration
Executing task: SyncTask.BuildFiles
Processing CLV-I-WIUPT ('Final Fantasy II'), size: 280640KB
"folder_back.png" did not need resizing, no processing done
Processed folder CLV-S-00000 ('Back'), size: 12KB
"folder.png" did not need resizing, no processing done
Processed folder CLV-S-00001 ('PSP'), size: 12KB
Processing CLV-P-SACCE ('CONTRA III THE ALIEN WARS'), size: 4KB
Processing CLV-P-SAALE ('Donkey Kong Country'), size: 4KB
Processing CLV-P-SAAJE ('EarthBound'), size: 4KB
Processing CLV-P-SABTE ('Final Fantasy III'), size: 4KB
Processing CLV-P-SAABE ('F-ZERO'), size: 4KB
Processing CLV-P-SAAQE ('Kirby Super Star'), size: 4KB
Processing CLV-P-SAAKE ('Kirby's Dream Course'), size: 4KB
Processing CLV-P-SABCE ('Mega Man X'), size: 4KB
Processing CLV-P-SABRE ('Secret of Mana'), size: 4KB
Processing CLV-P-SADGE ('Star Fox'), size: 4KB
Processing CLV-P-SADKE ('Star Fox 2'), size: 4KB
Processing CLV-P-SABHE ('Street Fighter II Turbo: Hyper Fighting'), size: 4KB
Processing CLV-P-SACBE ('Super Castlevania IV'), size: 4KB
Processing CLV-P-SABDE ('Super Ghouls'n Ghosts'), size: 4KB
Processing CLV-P-SAAFE ('Super Mario Kart'), size: 4KB
Processing CLV-P-SABQE ('Super Mario RPG: Legend of the Seven Stars'), size: 4KB
Processing CLV-P-SAAAE ('Super Mario World'), size: 4KB
Processing CLV-P-SAAHE ('Super Metroid'), size: 4KB
Processing CLV-P-SAAXE ('Super Punch-Out!!'), size: 4KB
Processing CLV-P-SAAEE ('The Legend of Zelda: A Link to the Past'), size: 4KB
Processing CLV-P-SADJE ('Yoshi's Island'), size: 4KB
Processing CLV-G-YRUUQ ('Battletoads'), size: 360KB
Processing CLV-G-ZWLLD ('Battletoads and Double Dragon'), size: 412KB
Processing CLV-G-IFGYB ('Shining Force'), size: 1136KB
Processing CLV-G-TWNIC ('Shining Force II'), size: 1420KB
"folder_back.png" did not need resizing, no processing done
Processed folder CLV-S-00000 ('Back'), size: 12KB
"megadrive2_jp.png" did not need resizing, no processing done
Processed folder CLV-S-00002 ('SEGA'), size: 12KB
Executing task: SyncTask.CheckLocalStorageRequirements
Exporting to folder: E:\hakchi\games\snes-eur
Drive: E:\ (NTFS)
Storage size: 1922,0MB, used by games: 0,0MB, free: 1906,0MB
Available for games: 1906,0MB
Executing task: SyncTask.CalculateLocalDiff
Executing task: SyncTask.SyncLocalGames
Exporting games: 360,3 MB
--- End of DEBUGLOG.TXT content ---

**Comment by Botanik1592** [comment]
> I have an error when try export psp game (or psx) to USB-drive.
> 
> UnauthorizedAccessException

I have a same error.

**Comment by Botanik1592** [comment]
> I have an error when try export psp game (or psx) to USB-drive.
> 
> UnauthorizedAccessException
> Access to the path 'D:\Games\hakchi2-ce-3.5.2-release\games\CLV-I-WIUPT\Final_Fantasy_II.iso' is denied.

I found a solution.
You need to remove "Only read" flag for "games" folder in your hakchi2 folder.

**Comment by leo60228** [comment]
hakchi2 is no longer supported. Please report your issue to hakchi2 CE (aka Hakchi 3) at https://github.com/TeamShinkansen/hakchi2/issues.
