### ISSUE TITLE
'Key-file'

### ISSUE THREAD

**Issue by WarValk72** [ClusterM/hakchi2#1469]
apparently my PC can no longer find "key-file" for dumping the kernel? can somebody help as to how to fix this? I just want to restore my mini snes

**Comment by WarValk72** [comment]
'C:\Users\MyName\Desktop\hakchi2_debug\temp\kernel\initramfs\key-file'.   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.ReadAllBytes(String path)
   at com.clusterrr.hakchi_gui.WorkerForm.DoKernelDump(String dumpPath, Int32 maxProgress, Int32 progress)
   at com.clusterrr.hakchi_gui.WorkerForm.FlashKernel()
   at com.clusterrr.hakchi_gui.WorkerForm.StartThread()


if this helps at all?

**Comment by juanpablo82mx** [comment]
I have the same problem, because i reinstall hakchi, you still have the issue?

**Comment by juanpablo82mx** [comment]
Try this:

https://www.youtube.com/watch?v=bsYEhurmAFE

**Comment by giampaolo** [comment]
Same problem here.
