### ISSUE TITLE
Problem to Dump Kernel in Snes Euro

### ISSUE THREAD

**Issue by juanpablo82mx** [ClusterM/hakchi2#1498]
Hi, i have some problems to dump the kernel in my Snes Euro, it already have the patch kernel, but i cant add games or modify it, my mistake is formatting the console by factory, i have the debug, please help me, thanks.

Base directory: C:\Users\jp\Downloads\hakchi2_debug
Loading config
Starting, version: 2.0.31.10
git commit: 4c9e52e
Executing task: LoadGames
Loading C:\Users\jp\Downloads\hakchi2_debug\data\nescarts.xml
Loading C:\Users\jp\Downloads\hakchi2_debug\data\snescarts.xml
SNES XML loading done, 786 roms total
NES XML loading done, 2150 roms total
Executing task: LoadGames
Executing task: DumpKernel
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> ... bytes
Device detection successful
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> ... bytes
Device detection successful
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> ... bytes
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> ... bytes
Error: Exception of type 'com.clusterrr.FelLib.FelParseException' was thrown.   at com.clusterrr.FelLib.AWUSBResponse..ctor(Byte[] data)
   at com.clusterrr.FelLib.Fel.FelRead(UInt32 length)
   at com.clusterrr.FelLib.Fel.VerifyDevice()
   at com.clusterrr.FelLib.Fel.Open(UInt16 vid, UInt16 pid)
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> ... bytes
Error: Exception of type 'com.clusterrr.FelLib.FelParseException' was thrown.   at com.clusterrr.FelLib.AWFELVerifyDeviceResponse..ctor(Byte[] data)
   at com.clusterrr.FelLib.Fel.VerifyDevice()
   at com.clusterrr.FelLib.Fel.Open(UInt16 vid, UInt16 pid)
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> ... bytes
Executing: C:\Users\jp\Downloads\hakchi2_debug\tools\unpackbootimg.exe
Arguments: -i "C:\Users\jp\Downloads\hakchi2_debug\temp\kernel.img" -o "C:\Users\jp\Downloads\hakchi2_debug\temp\kernel"
Directory: C:\Users\jp\Downloads\hakchi2_debug
Exit code: 0
Executing: C:\Users\jp\Downloads\hakchi2_debug\tools\xz.exe
Arguments: -dc "C:\Users\jp\Downloads\hakchi2_debug\temp\kernel\kernel.img-ramdisk.gz"
Directory: C:\Users\jp\Downloads\hakchi2_debug
Exit code: 0
Executing: C:\Users\jp\Downloads\hakchi2_debug\tools\cpio.exe
Arguments: -imd --no-preserve-owner --quiet -I "..\initramfs.cpio"
Directory: C:\Users\jp\Downloads\hakchi2_debug\temp\kernel\initramfs
Exit code: 0
Could not find file 'C:\Users\jp\Downloads\hakchi2_debug\temp\kernel\initramfs\key-file'.   en System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   en System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   en System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   en System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   en System.IO.File.ReadAllBytes(String path)
   en com.clusterrr.hakchi_gui.WorkerForm.DoKernelDump(String dumpPath, Int32 maxProgress, Int32 progress)
   en com.clusterrr.hakchi_gui.WorkerForm.StartThread()

**Comment by juanpablo82mx** [comment]
I run hackhi as administrator and i have a new error in log:

Executing: C:\Users\jp\Downloads\hakchi2.31_debug\hakchi2_debug\tools\unpackbootimg.exe
Arguments: -i "C:\Users\jp\Downloads\hakchi2.31_debug\hakchi2_debug\temp\kernel.img" -o "C:\Users\jp\Downloads\hakchi2.31_debug\hakchi2_debug\temp\kernel"
Directory: C:\Users\jp\Downloads\hakchi2.31_debug\hakchi2_debug
Exit code: 0
Executing: C:\Users\jp\Downloads\hakchi2.31_debug\hakchi2_debug\tools\xz.exe
Arguments: -dc "C:\Users\jp\Downloads\hakchi2.31_debug\hakchi2_debug\temp\kernel\kernel.img-ramdisk.gz"
Directory: C:\Users\jp\Downloads\hakchi2.31_debug\hakchi2_debug
Exit code: 0
Executing: C:\Users\jp\Downloads\hakchi2.31_debug\hakchi2_debug\tools\cpio.exe
Arguments: -imd --no-preserve-owner --quiet -I "..\initramfs.cpio"
Directory: C:\Users\jp\Downloads\hakchi2.31_debug\hakchi2_debug\temp\kernel\initramfs

**Comment by juanpablo82mx** [comment]
The solution:

https://www.youtube.com/watch?v=bsYEhurmAFE
