### ISSUE TITLE
Reproducible crash on v2.07 when selecting to not continue after an unsupported game is added

### ISSUE THREAD

**Issue by nm3210** [ClusterM/hakchi2#2]
I have downloaded and am running with the v2.07 zipped exe. 

When trying to add a game ('Solitaire (U).nes' in this case) with unsupported mappers I get the following message: 
> "Sorry, Solitaire (U).nes uses mapper #79 but this mapper is not supported by NES Mini and game probably will not start. Do you want to add this game anyway?". 

Then, when selecting **NO** the program crashes with the following exception text:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at com.clusterrr.hakchi_gui.MainForm.buttonAddGames_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by ClusterM** [comment]
Will be fixed in new version. Thanks1
