### ISSUE TITLE
v2.11 has blank options for Maximum Games per Page and when selected, hakchi2 crashes

### ISSUE THREAD

**Issue by asiansteev** [ClusterM/hakchi2#28]
I upgraded from v10 to v11 by extracting all files into v10 directory. I have 76 games loaded including the original 30. hakchi2's title bar confirms that I'm running v2.11. As seen in the screenshot below, I have extra blank options for max games per page. When selected, hakchi2 crashes.
I am on Windows10.
I expect it's related, but with 30 games per page, the folders do not work as expected. When any are selected, the first page of games just reloads. Autofire does not work either.

![capture](https://cloud.githubusercontent.com/assets/20084/22317029/3714c066-e33f-11e6-9f77-40f334663189.PNG)
![capture2](https://cloud.githubusercontent.com/assets/20084/22317039/3edafa22-e33f-11e6-8d6f-87ba166d2b8a.PNG)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Byte.Parse(String s, NumberStyles style, NumberFormatInfo info)
   at com.clusterrr.hakchi_gui.MainForm.toolStripMenuMaxGamesPerFolder_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8745 (WinRel.050727-8700)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
----------------------------------------
hakchi
    Assembly Version: 2.0.11.0
    Win32 Version: 2.0.11.0
    CodeBase: file:///C:/Users/steev/Downloads/hakchi2/hakchi.exe
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8750 (QFE.050727-8700)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8745 (WinRel.050727-8700)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8745 (WinRel.050727-8700)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.30729.8763 built by: WinRel
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
```

**Comment by asiansteev** [comment]
also probably related, there was no process for "Multistep uploading" like I expected. There was a single load like always.

**Comment by ClusterM** [comment]
Fixed, thank you!
