### ISSUE TITLE
Cannot use app to download boxart from Google

### ISSUE THREAD

**Issue by slewicki** [ClusterM/hakchi2#471]
When attempting to get box art for games I get the following exception:

Web request: https://www.google.com/search?q=Teenage+Mutant+Ninja+Turtles+IV+-+Turtles+in+Time+(snes+%7c+super+nintendo)+(box%7ccover)+art&source=lnms&tbm=isch
The read operation failed, see inner exception.   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadToEnd()
   at com.clusterrr.hakchi_gui.ImageGooglerForm.GetImageUrls(NesMiniApplication app) in D:\Projects\C#\hakchi2\ImageGooglerForm.cs:line 46
   at com.clusterrr.hakchi_gui.ImageGooglerForm.SearchThread(Object o) in D:\Projects\C#\hakchi2\ImageGooglerForm.cs:line 76
Web request: https://www.google.com/search?q=Megaman+X3+(snes+%7c+super+nintendo)+(box%7ccover)+art&source=lnms&tbm=isch
The read operation failed, see inner exception.   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadToEnd()
   at com.clusterrr.hakchi_gui.ImageGooglerForm.GetImageUrls(NesMiniApplication app) in D:\Projects\C#\hakchi2\ImageGooglerForm.cs:line 46
   at com.clusterrr.hakchi_gui.ImageGooglerForm.SearchThread(Object o) in D:\Projects\C#\hakchi2\ImageGooglerForm.cs:line 76

**Comment by shaman78** [comment]
there are also all covers if you want to do it manually 
(https://github.com/ramiabraham/cover-art-collection)

**Comment by Drakonas** [comment]
This has been fixed.
