### ISSUE TITLE
Can't Write to USB during NAND dump

### ISSUE THREAD

**Issue by larsy1995** [ClusterM/hakchi2#542]
Hi.
During NAND dump I get the error in the title. Tried different cables, ports and computers getting the same error. 
Here is a copy of what the debug screen says.

Trying to open device...
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
Can't write to USB   at com.clusterrr.FelLib.Fel.RunUbootCmd(String command, Boolean noreturn, OnFelProgress callback) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 414
   at com.clusterrr.FelLib.Fel.ReadFlash(UInt32 address, UInt32 length, OnFelProgress callback) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 338
   at com.clusterrr.hakchi_gui.WorkerForm.DoNandDump() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 602
   at com.clusterrr.hakchi_gui.WorkerForm.StartThread() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 264

**Comment by eisnerguy1** [comment]
I'm getting the same exact error message.
```
Trying to open device...
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
-> 16 bytes
Trying to open device...
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
Trying to open device...
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
Trying to open device...
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
Trying to open device...
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
Trying to open device...
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
Trying to open device...
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
Trying to open device...
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
Trying to open device...
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
Trying to open device...
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
Can't write to USB   at com.clusterrr.FelLib.Fel.RunUbootCmd(String command, Boolean noreturn, OnFelProgress callback) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 414
   at com.clusterrr.FelLib.Fel.ReadFlash(UInt32 address, UInt32 length, OnFelProgress callback) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 338
   at com.clusterrr.hakchi_gui.WorkerForm.DoNandDump() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 602
   at com.clusterrr.hakchi_gui.WorkerForm.StartThread() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 264
```

**Comment by joetheuseless** [comment]
same problem and no one seems to be responding to my ticket

**Comment by jfsb75** [comment]
same issue ....

**Comment by FJ000** [comment]
I am having a similar issue when trying to dump the NAND of the SNES Classic (US version).  
I am able to dump the original kernel.
I then attempt to dump the whole NAND.
I have tried on 2 different computers (windows 7 and windows 10).
hakchi2.21d
I have tried the web installer and debug versions, multiple USB ports (USB 2 and 3), running as administrator, turning off windows firewall, and turning off antivirus programs.
Would appreciate some help!  : )

> Executing task: DumpNand
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 32 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
Device detection successful
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 32 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
Device detection successful
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 32 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 128 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 12624 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 32 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 49152 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 48 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
-> 16 bytes
Error: Can't write to USB   at com.clusterrr.FelLib.Fel.WriteToUSB(Byte[] buffer) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 196
   at com.clusterrr.FelLib.Fel.FelWrite(Byte[] buffer) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 228
   at com.clusterrr.FelLib.Fel.FelRequest(RequestType command) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 250
   at com.clusterrr.FelLib.Fel.VerifyDevice() in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 264
   at com.clusterrr.FelLib.Fel.Open(UInt16 vid, UInt16 pid) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 155
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
Error: Can't write to USB   at com.clusterrr.FelLib.Fel.WriteToUSB(Byte[] buffer) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 196
   at com.clusterrr.FelLib.Fel.FelWrite(Byte[] buffer) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 227
   at com.clusterrr.FelLib.Fel.FelRequest(RequestType command) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 250
   at com.clusterrr.FelLib.Fel.VerifyDevice() in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 264
   at com.clusterrr.FelLib.Fel.Open(UInt16 vid, UInt16 pid) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 155
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
Error: Can't write to USB   at com.clusterrr.FelLib.Fel.WriteToUSB(Byte[] buffer) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 196
   at com.clusterrr.FelLib.Fel.FelWrite(Byte[] buffer) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 227
   at com.clusterrr.FelLib.Fel.FelRequest(RequestType command) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 250
   at com.clusterrr.FelLib.Fel.VerifyDevice() in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 264
   at com.clusterrr.FelLib.Fel.Open(UInt16 vid, UInt16 pid) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 155
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
Error: Can't write to USB   at com.clusterrr.FelLib.Fel.WriteToUSB(Byte[] buffer) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 196
   at com.clusterrr.FelLib.Fel.FelWrite(Byte[] buffer) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 227
   at com.clusterrr.FelLib.Fel.FelRequest(RequestType command) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 250
   at com.clusterrr.FelLib.Fel.VerifyDevice() in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 264
   at com.clusterrr.FelLib.Fel.Open(UInt16 vid, UInt16 pid) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 155
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
Error: Can't write to USB   at com.clusterrr.FelLib.Fel.WriteToUSB(Byte[] buffer) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 196
   at com.clusterrr.FelLib.Fel.FelWrite(Byte[] buffer) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 227
   at com.clusterrr.FelLib.Fel.FelRequest(RequestType command) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 250
   at com.clusterrr.FelLib.Fel.VerifyDevice() in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 264
   at com.clusterrr.FelLib.Fel.Open(UInt16 vid, UInt16 pid) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 155
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
Error: Can't write to USB   at com.clusterrr.FelLib.Fel.WriteToUSB(Byte[] buffer) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 196
   at com.clusterrr.FelLib.Fel.FelWrite(Byte[] buffer) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 227
   at com.clusterrr.FelLib.Fel.FelRequest(RequestType command) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 250
   at com.clusterrr.FelLib.Fel.VerifyDevice() in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 264
   at com.clusterrr.FelLib.Fel.Open(UInt16 vid, UInt16 pid) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 155
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
Error: Can't write to USB   at com.clusterrr.FelLib.Fel.WriteToUSB(Byte[] buffer) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 196
   at com.clusterrr.FelLib.Fel.FelWrite(Byte[] buffer) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 227
   at com.clusterrr.FelLib.Fel.FelRequest(RequestType command) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 250
   at com.clusterrr.FelLib.Fel.VerifyDevice() in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 264
   at com.clusterrr.FelLib.Fel.Open(UInt16 vid, UInt16 pid) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 155
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
Error: Can't write to USB   at com.clusterrr.FelLib.Fel.WriteToUSB(Byte[] buffer) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 196
   at com.clusterrr.FelLib.Fel.FelWrite(Byte[] buffer) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 227
   at com.clusterrr.FelLib.Fel.FelRequest(RequestType command) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 250
   at com.clusterrr.FelLib.Fel.VerifyDevice() in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 264
   at com.clusterrr.FelLib.Fel.Open(UInt16 vid, UInt16 pid) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 155
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
Error: Can't write to USB   at com.clusterrr.FelLib.Fel.WriteToUSB(Byte[] buffer) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 196
   at com.clusterrr.FelLib.Fel.FelWrite(Byte[] buffer) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 227
   at com.clusterrr.FelLib.Fel.FelRequest(RequestType command) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 250
   at com.clusterrr.FelLib.Fel.VerifyDevice() in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 264
   at com.clusterrr.FelLib.Fel.Open(UInt16 vid, UInt16 pid) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 155
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
Error: Can't write to USB   at com.clusterrr.FelLib.Fel.WriteToUSB(Byte[] buffer) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 196
   at com.clusterrr.FelLib.Fel.FelWrite(Byte[] buffer) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 227
   at com.clusterrr.FelLib.Fel.FelRequest(RequestType command) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 250
   at com.clusterrr.FelLib.Fel.VerifyDevice() in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 264
   at com.clusterrr.FelLib.Fel.Open(UInt16 vid, UInt16 pid) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 155
No answer from device   at com.clusterrr.FelLib.Fel.RunUbootCmd(String command, Boolean noreturn, OnFelProgress callback) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 432
   at com.clusterrr.FelLib.Fel.ReadFlash(UInt32 address, UInt32 length, OnFelProgress callback) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 361
   at com.clusterrr.hakchi_gui.WorkerForm.DoNandDump() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 632
   at com.clusterrr.hakchi_gui.WorkerForm.StartThread() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 284
No answer from device   at com.clusterrr.FelLib.Fel.RunUbootCmd(String command, Boolean noreturn, OnFelProgress callback) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 432
   at com.clusterrr.FelLib.Fel.ReadFlash(UInt32 address, UInt32 length, OnFelProgress callback) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 361
   at com.clusterrr.hakchi_gui.WorkerForm.DoNandDump() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 632
   at com.clusterrr.hakchi_gui.WorkerForm.StartThread() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 284
Closing main form
Saving config

**Comment by FJ000** [comment]
I wanted to add - I have **NOT** flashed the custom kernel.  
Is the custom kernel required to dump the whole NAND?

Also, I have run hakchi.exe as administrator in compatibility mode and granted full control permissions for all hakchi files.

**Comment by FJ000** [comment]
Have also tried version 2.0.20.15.  All has been tested using the original USB cable that came with the SNES classic.  (Have also tried with another USB cable with the same results).

Here is the debug info from version 2.0.20.15 if that helps isolate the same error as the above users:

> Trying to open device...
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
Can't write to USB   at com.clusterrr.FelLib.Fel.RunUbootCmd(String command, Boolean noreturn, OnFelProgress callback) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 414
   at com.clusterrr.FelLib.Fel.ReadFlash(UInt32 address, UInt32 length, OnFelProgress callback) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 338
   at com.clusterrr.hakchi_gui.WorkerForm.DoNandDump() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 602
   at com.clusterrr.hakchi_gui.WorkerForm.StartThread() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 264
Closing main form
Saving config

**Comment by scramble45** [comment]
Same issue on: v2.21d (internal version 2.0.21.56) - tried 3x cables 3x computers win7-win10. I just want to dump the factory NAND.

**Comment by Drakonas** [comment]
This seems to be a Ryzen issue on AMD's end. #620 Closing this as a duplicate. Please respond if you are not using Ryzen, and discuss on the #620 issue.

**Comment by FJ000** [comment]
Issue for me is now on 3 separate Intel PC's.  NOT AMD. One PC has USB 2.0 with Windows 7.  Other two have USB 2.0 and 3.0.  One running Windows 8.1 the other Windows 10.  Have tried all USB ports.  Two separate usb cables.  Have tried up to hakchi2 version 2.21e.  I have not flashed the new kernel.  Only dumped the original kernel, which was successful.  Since the same problem is present on 3 PC's with different configurations I am not ruling out the possibility that the fault could be my own.  Still, I am no further at figuring out the problem.
