### ISSUE TITLE
Error when trying to flash original or Custom Kernel in 2.21b - Exception of type 'com.clusterrr.FelLib.FelParseException' was thrown. 

### ISSUE THREAD

**Issue by OliverUlm** [ClusterM/hakchi2#634]
This is the exception detail given by the Debug version (version 2.0.21.30)

Exception of type 'com.clusterrr.FelLib.FelParseException' was thrown.   at com.clusterrr.FelLib.AWUSBResponse..ctor(Byte[] data) in D:\Projects\C#\hakchi2\FelLib\AWUSBResponse.cs:line 22
   at com.clusterrr.FelLib.Fel.FelWrite(Byte[] buffer) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 229
   at com.clusterrr.FelLib.Fel.FelRequest(RequestType command, UInt32 address, UInt32 length) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 259
   at com.clusterrr.FelLib.Fel.ReadMemory(UInt32 address, UInt32 length, OnFelProgress callback) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 318
   at com.clusterrr.FelLib.Fel.RunUbootCmd(String command, Boolean noreturn, OnFelProgress callback) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 406
   at com.clusterrr.FelLib.Fel.ReadFlash(UInt32 address, UInt32 length, OnFelProgress callback) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 361
   at com.clusterrr.hakchi_gui.WorkerForm.FlashKernel() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 571
   at com.clusterrr.hakchi_gui.WorkerForm.StartThread() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 281

**Comment by Dark-talon** [comment]
Same issue.

**Comment by hoderer** [comment]
Same here. Hoping for a fix. Never had such problems with previous versions.

**Comment by conantroisdet** [comment]
Same here too. I had this issue on 2.20, but switching from the web installer version to the portable version unzipped on the same drive than my roms solved it.

**Comment by From90th** [comment]
The same issue! Who knows where can i get the original snes mini kernel? I have deleted it from documents/hakchi folder.

**Comment by nigka** [comment]
Same issue here. Waiting for news...

**Comment by ClusterM** [comment]
Try version 2.0.21.31

**Comment by hoderer** [comment]
Same error with version 2.0.21.31 (portable)

**Comment by OliverUlm** [comment]
2.0.21.31 still shows the issue - however it now looks as if the exception is generated twice in the debug log. Is there any additional information logged that could help diagnosing that issue?

Error: Exception of type 'com.clusterrr.FelLib.FelParseException' was thrown.   at com.clusterrr.FelLib.AWUSBResponse..ctor(Byte[] data) in D:\Projects\C#\hakchi2\FelLib\AWUSBResponse.cs:line 22
   at com.clusterrr.FelLib.Fel.FelRead(UInt32 length) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 241
   at com.clusterrr.FelLib.Fel.VerifyDevice() in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 274
   at com.clusterrr.FelLib.Fel.Open(UInt16 vid, UInt16 pid) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 155
-> 32 bytes
-> 16 bytes
<- 13 bytes
<- 5 bytes
Exception of type 'com.clusterrr.FelLib.FelParseException' was thrown.   at com.clusterrr.FelLib.AWUSBResponse..ctor(Byte[] data) in D:\Projects\C#\hakchi2\FelLib\AWUSBResponse.cs:line 22
   at com.clusterrr.FelLib.Fel.FelWrite(Byte[] buffer) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 229
   at com.clusterrr.FelLib.Fel.FelRequest(RequestType command, UInt32 address, UInt32 length) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 259
   at com.clusterrr.FelLib.Fel.ReadMemory(UInt32 address, UInt32 length, OnFelProgress callback) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 318
   at com.clusterrr.FelLib.Fel.RunUbootCmd(String command, Boolean noreturn, OnFelProgress callback) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 406
   at com.clusterrr.FelLib.Fel.ReadFlash(UInt32 address, UInt32 length, OnFelProgress callback) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 361
   at com.clusterrr.hakchi_gui.WorkerForm.FlashKernel() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 571
   at com.clusterrr.hakchi_gui.WorkerForm.StartThread() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 281

**Comment by ClusterM** [comment]
Found it. Wait a minute.

**Comment by ClusterM** [comment]
Fixed. Please update.
And sorry :(

**Comment by benc-uk** [comment]
2.0.21.32 fixed it for me
I wonder if we can have less scary error when the kernel MD5 checksum doesn't match. I assume it doesn't match as as we're re-flashing an already modded machine, rather than a base/factory kernel

**Comment by From90th** [comment]
MD5 checksum doesn't match again. Can I go on? Why it doesn't matches?

**Comment by amayatsky** [comment]
How do I update the web-installer version?
I don't see any prompt or a "Check for Update" button in the UI.

**Comment by Linkinworm** [comment]
How do we grab the internal versions? didnt' want to make a new issue post
