### ISSUE TITLE
WebInstaller fails

### ISSUE THREAD

**Issue by Linkinworm** [ClusterM/hakchi2#635]
This is the log file it produces, i've tried it on the 2.20 release and the latest and both seem to fail for me, any idea why?

PLATFORM VERSION INFO
	Windows 			: 10.0.15063.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.2046.0 built by: NET47REL1
	clr.dll 			: 4.7.2110.0 built by: NET47REL1LAST
	dfdll.dll 			: 4.7.2046.0 built by: NET47REL1
	dfshim.dll 			: 10.0.15063.0 (WinBuild.160101.0800)

SOURCES
	Deployment url			: http://clusterrr.com/soft/hakchi2/hakchi.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of http://clusterrr.com/soft/hakchi2/hakchi.application resulted in exception. Following failure messages were detected:
		+ Downloading http://clusterrr.com/soft/hakchi2/hakchi.application did not succeed.
		+ Unable to connect to the remote server
		+ A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 94.253.14.226:80

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [10/10/2017 18:18:17] : Activation of http://clusterrr.com/soft/hakchi2/hakchi.application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [10/10/2017 18:18:38] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading http://clusterrr.com/soft/hakchi2/hakchi.application did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			at System.Deployment.Application.DownloadManager.DownloadManifestAsRawFile(Uri& sourceUri, String targetPath, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirectBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- Unable to connect to the remote server
		- Source: System
		- Stack trace:
			at System.Net.HttpWebRequest.GetResponse()
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
		--- Inner Exception ---
		System.Net.Sockets.SocketException
		- A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 94.253.14.226:80
		- Source: System
		- Stack trace:
			at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
			at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by benc-uk** [comment]
I'm getting the same
I think the installer pulls down the rest of the app from cluster's own website (http://clusterrr.com) I expect it is being hammered/overloaded/exceeded its bandwidth

**Comment by ClusterM** [comment]
Seems like it :( Need to host it elsewhere.

**Comment by theDarkFrenchy** [comment]
same problem here... but you are already aware of this problem....

**Comment by ClusterM** [comment]
Try to wait a bit and try again. My server's HDD is crackling as mad.

**Comment by sks316** [comment]
Until Cluster can resolve the issue, wait or use the portable version.

**Comment by theDarkFrenchy** [comment]
OK thanks to both of you.
I'll wait , don't' worry !
