### ISSUE TITLE
Error On Flash - Error: Exception of type 'com.clusterrr.FelLib.FelParseException'

### ISSUE THREAD

**Issue by Darky2k1** [ClusterM/hakchi2#676]
Errors on Flash - Seems to have worked but error in logs

`Trying to verify device
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 32 bytes
<- 16 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
Error: Exception of type 'com.clusterrr.FelLib.FelParseException' was thrown.   at com.clusterrr.FelLib.AWFELVerifyDeviceResponse..ctor(Byte[] data) in D:\Projects\C#\hakchi2\FelLib\AWFELVerifyDeviceResponse.cs:line 26
   at com.clusterrr.FelLib.Fel.VerifyDevice() in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 275
   at com.clusterrr.FelLib.Fel.Open(UInt16 vid, UInt16 pid) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 155
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device`

**Comment by ClusterM** [comment]
Version?

**Comment by Darky2k1** [comment]
@ClusterM 2.21b_debug

**Comment by EdGe7x** [comment]
In trying to dump the kernel, 2.0.21.30 gave me this same error but 2.0.21.32 is working for me.

**Comment by EdGe7x** [comment]
Debug version 2.0.21.33 is also working.

**Comment by RaZer0k** [comment]
**same here** 
Error: USB read error: IoTimedOut   at com.clusterrr.FelLib.Fel.ReadFromUSB(Byte[] buffer, Int32 offset, Int32 length) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 208
   at com.clusterrr.FelLib.Fel.ReadFromUSB(UInt32 length) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 217
   at com.clusterrr.FelLib.Fel.FelWrite(Byte[] buffer) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 229
   at com.clusterrr.FelLib.Fel.FelRequest(RequestType command) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 250
   at com.clusterrr.FelLib.Fel.VerifyDevice() in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 264
   at com.clusterrr.FelLib.Fel.Open(UInt16 vid, UInt16 pid) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 155
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 32 bytes
<- 16 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
Error: Exception of type 'com.clusterrr.FelLib.FelParseException' was thrown.   at com.clusterrr.FelLib.AWFELVerifyDeviceResponse..ctor(Byte[] data) in D:\Projects\C#\hakchi2\FelLib\AWFELVerifyDeviceResponse.cs:line 26
   at com.clusterrr.FelLib.Fel.VerifyDevice() in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 275
   at com.clusterrr.FelLib.Fel.Open(UInt16 vid, UInt16 pid) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 155
Checking USB endpoints...

Version 2.0.21.32

**Comment by nex86** [comment]
yea same error pops up for me in console output in 2.0.21.32 when doing transfer operations like flashing/dumping Kernel or dumping nand.
Tried using different USB Ports, same issue.
leaving my SNESC Mini untouched now until this is fixed.


```
Error: Exception of type 'com.clusterrr.FelLib.FelParseException' was thrown.   at com.clusterrr.FelLib.AWFELVerifyDeviceResponse..ctor(Byte[] data) in D:\Projects\C#\hakchi2\FelLib\AWFELVerifyDeviceResponse.cs:line 26
   at com.clusterrr.FelLib.Fel.VerifyDevice() in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 275
   at com.clusterrr.FelLib.Fel.Open(UInt16 vid, UInt16 pid) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 155
```




```
Error: USB read error: IoTimedOut   at com.clusterrr.FelLib.Fel.ReadFromUSB(Byte[] buffer, Int32 offset, Int32 length) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 208
   at com.clusterrr.FelLib.Fel.ReadFromUSB(UInt32 length) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 217
   at com.clusterrr.FelLib.Fel.FelWrite(Byte[] buffer) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 229
   at com.clusterrr.FelLib.Fel.FelRequest(RequestType command) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 250
   at com.clusterrr.FelLib.Fel.VerifyDevice() in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 264
   at com.clusterrr.FelLib.Fel.Open(UInt16 vid, UInt16 pid) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 155
```

**Comment by nex86** [comment]
I don't think you need to worry about these errors.
they only show up when hakchi establishes a new connection for whatever reason.
I did a nand dump with 2.20.15 and 2.0.21.32 and the hashes of the output files are the same.
