### ISSUE TITLE
Auto update failed with error message

### ISSUE THREAD

**Issue by haywire27** [ClusterM/hakchi2#731]
Trying to update 2.21.40 to latest build.  Keep getting an error message nearing the end of download with auto update.

Here are the details:

`
PLATFORM VERSION INFO
	Windows 			: 6.2.9200.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.0.30319.33440 built by: FX45W81RTMREL
	clr.dll 			: 4.6.96.0 built by: NETFXREL2STAGE
	dfdll.dll 			: 4.0.30319.33440 built by: FX45W81RTMREL
	dfshim.dll 			: 6.3.9600.16384 (winblue_rtm.130821-1623)

SOURCES
	Deployment url			: file:///C:/Users/BL/AppData/Roaming/Microsoft/Internet%20Explorer/Quick%20Launch/User%20Pinned/TaskBar/hakchi2.appref-ms%7C
						Server		: Apache/2.4.18 (Ubuntu)
	Deployment Provider url		: http://clusterrr.com/soft/hakchi2/hakchi.application
	Application url			: http://clusterrr.com/soft/hakchi2/Application%20Files/hakchi_2_0_21_42/hakchi.exe.manifest
						Server		: Apache/2.4.18 (Ubuntu)

IDENTITIES
	Application Identity		: hakchi.exe, Version=2.0.21.42, Culture=neutral, PublicKeyToken=ac3ed33da7b15b8c, processorArchitecture=msil, type=win32

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\BL\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\hakchi2.appref-ms| resulted in exception. Following failure messages were detected:
		+ Downloading http://clusterrr.com/soft/hakchi2/Application Files/hakchi_2_0_21_42/mods/hmods/copyleft.hmod did not succeed.
		+ Unable to connect to the remote server
		+ A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 94.253.14.226:80

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [10/12/2017 9:20:14 AM] : Activation of C:\Users\BL\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\hakchi2.appref-ms| has started.
	* [10/12/2017 9:20:14 AM] : Performing necessary update check as specified by the deployment.
	* [10/12/2017 9:20:14 AM] : Consuming new update.
	* [10/12/2017 9:20:17 AM] : Installation of the application has started.
	* [10/12/2017 9:20:18 AM] : Processing of application manifest has successfully completed.
	* [10/12/2017 9:20:18 AM] : Found compatible runtime version 2.0.50727.
	* [10/12/2017 9:20:18 AM] : Detecting dependent assembly Sentinel.v3.5Client, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=msil using Sentinel.v3.5Client, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=msil.
	* [10/12/2017 9:20:18 AM] : Detecting dependent assembly System.Data.Entity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=msil using System.Data.Entity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=msil.
	* [10/12/2017 9:20:18 AM] : Detecting dependent assembly WindowsBase, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=msil using WindowsBase, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=msil.
	* [10/12/2017 9:20:18 AM] : Detecting dependent assembly System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=msil using System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=msil.
	* [10/12/2017 9:20:18 AM] : Detecting dependent assembly System.Data.Entity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=msil using System.Data.Entity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=msil.
	* [10/12/2017 9:20:18 AM] : Request of trust and detection of platform is complete.

ERROR DETAILS
	Following errors were detected during this operation.
	* [10/12/2017 9:20:42 AM] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading http://clusterrr.com/soft/hakchi2/Application Files/hakchi_2_0_21_42/mods/hmods/copyleft.hmod did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState)
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.ConsumeUpdatedDeployment(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentUpdate(SubscriptionState& subState, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ProcessOrFollowShortcut(String shortcutFile, String& errorPageUrl, TempFile& deployFile)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- Unable to connect to the remote server
		- Source: System
		- Stack trace:
			at System.Net.HttpWebRequest.GetResponse()
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
		--- Inner Exception ---
		System.Net.Sockets.SocketException
		- A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 94.253.14.226:80
		- Source: System
		- Stack trace:
			at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
			at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.`

**Comment by Drakonas** [comment]
Have you tried manually updating?

**Comment by Drakonas** [comment]
Closing this issue as the OP is not responding.
