### ISSUE TITLE
Web Installer for 2.21c unable to connect to your server to download hakchi.application

### ISSUE THREAD

**Issue by zimmertr** [ClusterM/hakchi2#737]
http://clusterrr.com/soft/hakchi2/hakchi.application

**LOG:**
```
The following properties have been set:
Property: [AdminUser] = true {boolean}
Property: [InstallMode] = HomeSite {string}
Property: [NTProductType] = 1 {int}

>snip<

'.NET Framework 3.5 SP1' RunCheck result: No Install Needed
Launching Application.
URLDownloadToCacheFile failed with HRESULT '-2146697211'
Error: An error occurred trying to download 'http://clusterrr.com/soft/hakchi2/hakchi.application'.
```

**Comment by zimmertr** [comment]
Log from Web Installer when attempting a manual install:

```
PLATFORM VERSION INFO
	Windows 			: 10.0.15063.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.2046.0 built by: NET47REL1
	clr.dll 			: 4.7.2110.0 built by: NET47REL1LAST
	dfdll.dll 			: 4.7.2046.0 built by: NET47REL1
	dfshim.dll 			: 10.0.15063.0 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///C:/Users/tzimmerman/Downloads/hakchi.application
	Deployment Provider url		: http://clusterrr.com/soft/hakchi2/hakchi.application
						Server		: Apache/2.4.18 (Ubuntu)
	Application url			: http://clusterrr.com/soft/hakchi2/Application%20Files/hakchi_2_0_21_42/hakchi.exe.manifest
						Server		: Apache/2.4.18 (Ubuntu)

IDENTITIES
	Deployment Identity		: hakchi.application, Version=2.0.21.42, Culture=neutral, PublicKeyToken=ac3ed33da7b15b8c, processorArchitecture=msil
	Application Identity		: hakchi.exe, Version=2.0.21.42, Culture=neutral, PublicKeyToken=ac3ed33da7b15b8c, processorArchitecture=msil, type=win32

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\tzimmerman\Downloads\hakchi.application resulted in exception. Following failure messages were detected:
		+ Downloading http://clusterrr.com/soft/hakchi2/Application Files/hakchi_2_0_21_42/folder_images/gb_dmg.png did not succeed.
		+ Unable to connect to the remote server
		+ A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 94.253.14.226:80

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [10/12/2017 1:52:18 PM] : Activation of C:\Users\tzimmerman\Downloads\hakchi.application has started.
	* [10/12/2017 1:52:18 PM] : Processing of deployment manifest has successfully completed.
	* [10/12/2017 1:52:18 PM] : Installation of the application has started.
	* [10/12/2017 1:52:19 PM] : Processing of application manifest has successfully completed.
	* [10/12/2017 1:52:21 PM] : Found compatible runtime version 2.0.50727.
	* [10/12/2017 1:52:22 PM] : Detecting dependent assembly Sentinel.v3.5Client, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=msil using Sentinel.v3.5Client, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=msil.
	* [10/12/2017 1:52:22 PM] : Detecting dependent assembly System.Data.Entity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=msil using System.Data.Entity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=msil.
	* [10/12/2017 1:52:22 PM] : Detecting dependent assembly WindowsBase, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=msil using WindowsBase, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=msil.
	* [10/12/2017 1:52:22 PM] : Detecting dependent assembly System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=msil using System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=msil.
	* [10/12/2017 1:52:22 PM] : Detecting dependent assembly System.Data.Entity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=msil using System.Data.Entity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=msil.
	* [10/12/2017 1:52:22 PM] : Request of trust and detection of platform is complete.

ERROR DETAILS
	Following errors were detected during this operation.
	* [10/12/2017 1:53:52 PM] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading http://clusterrr.com/soft/hakchi2/Application Files/hakchi_2_0_21_42/folder_images/gb_dmg.png did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- Unable to connect to the remote server
		- Source: System
		- Stack trace:
			at System.Net.HttpWebRequest.GetResponse()
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
		--- Inner Exception ---
		System.Net.Sockets.SocketException
		- A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 94.253.14.226:80
		- Source: System
		- Stack trace:
			at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
			at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.
```

**Comment by The-MAZZTer** [comment]
It wasn't working for me either but it just started working again.

**Comment by eramdev** [comment]
Try to run the web installer as administrator.

**Comment by The-MAZZTer** [comment]
That will not do anything. It is/was a problem with the clusterrr.com web server. I opened a web browser to the http://clusterrr.com/soft/hakchi2/hakchi.application url before making my last post and it timed out. A little later it started working. This is not something the end user can fix.

**Comment by zimmertr** [comment]
I agree with The-mazzter. I posted to alert the dev of his unstable server.

**Comment by ClusterM** [comment]
Try it now please. I bought hosting.
