### ISSUE TITLE
2.21e fails to start after using web installer

### ISSUE THREAD

**Issue by jdpgrailsdev** [ClusterM/hakchi2#879]
After attempting to upgrade from 2.21d to 2.21e via the web installer, a prompt appears indicating that the application failed to start.  Clicking on details reveals the following information:

```
PLATFORM VERSION INFO
	Windows 			: 10.0.15063.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.2046.0 built by: NET47REL1
	clr.dll 			: 4.7.2115.0 built by: NET47REL1LAST
	dfdll.dll 			: 4.7.2046.0 built by: NET47REL1
	dfshim.dll 			: 10.0.15063.0 (WinBuild.160101.0800)

SOURCES
	Deployment url			: http://software.clusterrr.com/hakchi2/hakchi.application
						Server		: nginx/1.10.1

IDENTITIES
	Deployment Identity		: hakchi.application, Version=2.0.21.60, Culture=neutral, PublicKeyToken=ac3ed33da7b15b8c, processorArchitecture=msil

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of http://software.clusterrr.com/hakchi2/hakchi.application resulted in exception. Following failure messages were detected:
		+ Value does not fall within the expected range.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [10/20/2017 9:02:45 AM] : Activation of http://software.clusterrr.com/hakchi2/hakchi.application has started.
	* [10/20/2017 9:02:45 AM] : Processing of deployment manifest has successfully completed.

ERROR DETAILS
	Following errors were detected during this operation.
	* [10/20/2017 9:02:45 AM] System.ArgumentException
		- Value does not fall within the expected range.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.NativeMethods.CorLaunchApplication(UInt32 hostType, String applicationFullName, Int32 manifestPathsCount, String[] manifestPaths, Int32 activationDataCount, String[] activationData, PROCESS_INFORMATION processInformation)
			at System.Deployment.Application.ComponentStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.SubscriptionStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.ApplicationActivator.Activate(DefinitionAppId appId, AssemblyManifest appManifest, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	* Transaction at [10/20/2017 9:02:45 AM]
		+ System.Deployment.Internal.Isolation.StoreOperationSetDeploymentMetadata
			- Status: Set
			- HRESULT: 0x0
		+ System.Deployment.Internal.Isolation.StoreTransactionOperationType (27)
			- HRESULT: 0x0
```

I am running Windows 10 64-bit (VirtualBox VM).  All previous versions launched after using the web installer.  I am going to attempt to use the other distributions to see if I can get them to start.

**Comment by jdpgrailsdev** [comment]
Downloading the 2.21e distribution zip and launching the application from it works.  I was also able to successfully revert the application back to 2.21d via the uninstaller and that launches as well.

**Comment by jdpgrailsdev** [comment]
I am going to close this issue, as I re-attempted to install using the 2.21e web installer and the application launches after the second attempt.  Not sure what went wrong during the first one, but it appears to be fixed after deleting the downloaded web installer binary and re-attempting.
