### ISSUE TITLE
hakchi2.21e regularly crashing. Debug log attached

### ISSUE THREAD

**Issue by Babbonz** [ClusterM/hakchi2#905]
When playing games i get regular crashes with the screen going either red or black and freezing. I've attached a hakchi2.21e dubug log of the last crash so hopefuly this is helpful?
I was playing street fighter 2 via mame2000 hmod and it quited out. I've also tried unstalling all traces of retroarch and mame2000 (its the only hmod I currently use but have the same issues with other mods previously like snes9x etc). I've reverted to just using canoe again and unistalled retroarch and i get the same crahses with just stock games too?

Debug log below (I hope it's recorded it OK?):

Base directory: C:\Users\Baboon\Desktop\nes mini\SNES\hakchi2.21e_debug\hakchi2_debug
Loading config
Starting, version: 2.0.21.60
Loading games
Loading C:\Users\Baboon\Desktop\nes mini\SNES\hakchi2.21e_debug\hakchi2_debug\data\nescarts.xml
Loading C:\Users\Baboon\Desktop\nes mini\SNES\hakchi2.21e_debug\hakchi2_debug\data\snescarts.xml
SNES XML loading done, 786 roms total
NES XML loading done, 2150 roms total
clovershell connected
[ -d /var/lib/hakchi/firmware/ ] && [ -f /var/lib/hakchi/firmware/*.hsqs ] && echo YES || echo NO # exit code: 0
cat /etc/clover/boardtype # exit code: 0
cat /etc/clover/REGION # exit code: 0
Detected board: dp-shvc
Detected region: EUR
df /dev/nandc | tail -n 1 | awk '{ print $2 " | " $3 " | " $4 }' # exit code: 0
mount | grep /var/lib/clover # exit code: 1
mkdir -p /var/lib/hakchi/rootfs/usr/share/games/ && du -s /var/lib/hakchi/rootfs/usr/share/games/ | awk '{ print $1 }' # exit code: 0
mkdir -p /var/lib/clover/profiles/0/ && du -s /var/lib/clover/profiles/0/ | awk '{ print $1 }' # exit code: 0
NANDC size: 290.6MB, used: 144.9MB, free: 130.7MB
Used by games: 121.9MB
Used by save-states: 0.2MB
Used by other files (mods, configs, etc.): 22.8MB
Available for games: 252.6MB
no answer from device   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 266
write error: IoTimedOut
write error: IoTimedOut
write error: IoTimedOut
write error: IoTimedOut
write error: IoTimedOut
write error: IoTimedOut
write error: IoTimedOut
write error: IoTimedOut
write error: IoTimedOut
write error: IoTimedOut
clovershell disconnected
clovershell connected
kill all shell: write error - IoTimedOut   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 400
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 250
clovershell connected
kill all shell: write error - IoTimedOut   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 400
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 250
clovershell connected
kill all shell: write error - IoTimedOut   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 400
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 250
clovershell connected
kill all shell: write error - IoTimedOut   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 400
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 250
clovershell connected
kill all shell: write error - IoTimedOut   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 400
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 250
clovershell connected
kill all shell: write error - IoTimedOut   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 400
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 250
clovershell connected
kill all shell: write error - IoTimedOut   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 400
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 250
clovershell connected
kill all shell: write error - IoTimedOut   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 400
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 250
clovershell connected
kill all shell: write error - IoTimedOut   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 400
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 250
clovershell connected
kill all shell: write error - IoTimedOut   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 400
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 250
clovershell connected
kill all shell: write error - IoTimedOut   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 400
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 250
clovershell connected
kill all shell: write error - IoTimedOut   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 400
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 250
clovershell connected
kill all shell: write error - IoTimedOut   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 400
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 250
clovershell connected
kill all shell: write error - IoTimedOut   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 400
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 250
clovershell connected
kill all shell: write error - IoTimedOut   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 400
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 250
clovershell connected
kill all shell: write error - IoTimedOut   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 400
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 250
clovershell connected
kill all shell: write error - IoTimedOut   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 400
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 250
clovershell connected
kill all shell: write error - IoTimedOut   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 400
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 250
clovershell connected
kill all shell: write error - IoTimedOut   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 400
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 250
clovershell connected
kill all shell: write error - IoTimedOut   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 400
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 250
clovershell connected
kill all shell: write error - IoTimedOut   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 400
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 250
clovershell connected
kill all shell: write error - IoTimedOut   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 400
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 250
clovershell connected
kill all shell: write error - IoTimedOut   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 400
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 250
clovershell connected
kill all shell: write error - IoTimedOut   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 400
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 250
clovershell connected
kill all shell: write error - IoTimedOut   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 400
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 250
clovershell connected
kill all shell: write error - IoTimedOut   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 400
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 250
clovershell connected
kill all shell: write error - Win32Error   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 400
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 250

**Comment by Drakonas** [comment]
Ask this from the person who made the mame2000 hmod, this is out of ClusterM's hands as he did not have anything to do with that core.

**Comment by Babbonz** [comment]
This has nothing to do with that hmod  as I get the same crashes when retro arch and all hmods are also unistalled and I just use the default canoe enu (as I posted already above if you read the second paragraph) )? So your reply makes no sense!

**Comment by Babbonz** [comment]
I think this maybe related to power though as when I use a mains plug it seems to hardly crash now compared to previously using a USB port on my uhd tv?

**Comment by Drakonas** [comment]
I am sorry. I have spent the last 7 hours trying to clear up some of these tickets. Yes, using a TV/monitor/USB hub/game console usb port often does not provide enough power to the SNES classic. Has your issue been resolved?

**Comment by Babbonz** [comment]
I'm at work now but will test again tonight and confirm if all sorted. Thanks for the reply!

**Comment by Babbonz** [comment]
Yes this definitely looks like the power issue as have been playing for over an hour using it connected to mains and it hasn't crashed once! It's weird as using the USB port on my tv does work (it's fine for my pi, nvidia shield etc) as it plays happily enough for a while before the crashing? Anyway I guess consider this resolved.

**Comment by Drakonas** [comment]
I guess some TV's may provide enough power. Thank you for letting us know. :)
